//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parikmaherskaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Acounting = new HashSet<Acounting>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IdManufacturer { get; set; }
    
        public virtual ICollection<Acounting> Acounting { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
