//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parikmaherskaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acounting> Acounting { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Manufacturer> Manufacturer { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<View_1> View_1 { get; set; }
    }
}
