//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parikmaherskaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public System.DateTime DateDelivery { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Name { get; set; }
    }
}
